// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinFormApp.Models;

namespace WinFormApp.Migrations
{
    [DbContext(typeof(CoffeeShopContext))]
    [Migration("20250921101547_InitData")]
    partial class InitData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WinFormApp.Models.Account", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("UserName");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            UserName = "admin",
                            DisplayName = "Administrator",
                            PassWord = "123456",
                            Type = 1
                        },
                        new
                        {
                            UserName = "john_doe",
                            DisplayName = "John Doe",
                            PassWord = "123456",
                            Type = 0
                        },
                        new
                        {
                            UserName = "jane_smith",
                            DisplayName = "Jane Smith",
                            PassWord = "123456",
                            Type = 0
                        },
                        new
                        {
                            UserName = "michael",
                            DisplayName = "Michael Johnson",
                            PassWord = "123456",
                            Type = 0
                        },
                        new
                        {
                            UserName = "emily",
                            DisplayName = "Emily Davis",
                            PassWord = "123456",
                            Type = 0
                        },
                        new
                        {
                            UserName = "david",
                            DisplayName = "David Wilson",
                            PassWord = "123456",
                            Type = 0
                        },
                        new
                        {
                            UserName = "sarah",
                            DisplayName = "Sarah Brown",
                            PassWord = "123456",
                            Type = 0
                        },
                        new
                        {
                            UserName = "chris",
                            DisplayName = "Chris Lee",
                            PassWord = "123456",
                            Type = 0
                        },
                        new
                        {
                            UserName = "amanda",
                            DisplayName = "Amanda Miller",
                            PassWord = "123456",
                            Type = 0
                        },
                        new
                        {
                            UserName = "matthew",
                            DisplayName = "Matthew Garcia",
                            PassWord = "123456",
                            Type = 0
                        });
                });

            modelBuilder.Entity("WinFormApp.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTable")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTable");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("WinFormApp.Models.BillInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("IdBill")
                        .HasColumnType("int");

                    b.Property<int>("IdFood")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdBill");

                    b.HasIndex("IdFood");

                    b.ToTable("BillInfos");
                });

            modelBuilder.Entity("WinFormApp.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdCategory");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdCategory = 1,
                            Name = "Espresso",
                            Price = 2.5
                        },
                        new
                        {
                            Id = 2,
                            IdCategory = 1,
                            Name = "Latte",
                            Price = 3.5
                        },
                        new
                        {
                            Id = 3,
                            IdCategory = 1,
                            Name = "Cappuccino",
                            Price = 3.7999999999999998
                        },
                        new
                        {
                            Id = 4,
                            IdCategory = 1,
                            Name = "Americano",
                            Price = 2.7999999999999998
                        },
                        new
                        {
                            Id = 5,
                            IdCategory = 2,
                            Name = "Green Tea",
                            Price = 2.0
                        },
                        new
                        {
                            Id = 6,
                            IdCategory = 2,
                            Name = "Black Tea",
                            Price = 2.0
                        },
                        new
                        {
                            Id = 7,
                            IdCategory = 2,
                            Name = "Herbal Tea",
                            Price = 2.5
                        },
                        new
                        {
                            Id = 8,
                            IdCategory = 2,
                            Name = "Milk Tea",
                            Price = 3.0
                        },
                        new
                        {
                            Id = 9,
                            IdCategory = 3,
                            Name = "Mango Smoothie",
                            Price = 4.5
                        },
                        new
                        {
                            Id = 10,
                            IdCategory = 3,
                            Name = "Strawberry Smoothie",
                            Price = 4.5
                        },
                        new
                        {
                            Id = 11,
                            IdCategory = 3,
                            Name = "Banana Smoothie",
                            Price = 4.0
                        },
                        new
                        {
                            Id = 12,
                            IdCategory = 3,
                            Name = "Avocado Smoothie",
                            Price = 5.0
                        },
                        new
                        {
                            Id = 13,
                            IdCategory = 4,
                            Name = "Croissant",
                            Price = 2.5
                        },
                        new
                        {
                            Id = 14,
                            IdCategory = 4,
                            Name = "Muffin",
                            Price = 2.0
                        },
                        new
                        {
                            Id = 15,
                            IdCategory = 4,
                            Name = "Cheesecake",
                            Price = 3.5
                        },
                        new
                        {
                            Id = 16,
                            IdCategory = 4,
                            Name = "Chocolate Cake",
                            Price = 3.7999999999999998
                        },
                        new
                        {
                            Id = 17,
                            IdCategory = 5,
                            Name = "Ham Sandwich",
                            Price = 4.0
                        },
                        new
                        {
                            Id = 18,
                            IdCategory = 5,
                            Name = "Chicken Sandwich",
                            Price = 4.5
                        },
                        new
                        {
                            Id = 19,
                            IdCategory = 5,
                            Name = "Veggie Sandwich",
                            Price = 3.7999999999999998
                        },
                        new
                        {
                            Id = 20,
                            IdCategory = 6,
                            Name = "Orange Juice",
                            Price = 3.0
                        },
                        new
                        {
                            Id = 21,
                            IdCategory = 6,
                            Name = "Apple Juice",
                            Price = 3.0
                        },
                        new
                        {
                            Id = 22,
                            IdCategory = 6,
                            Name = "Carrot Juice",
                            Price = 3.2000000000000002
                        },
                        new
                        {
                            Id = 23,
                            IdCategory = 7,
                            Name = "Vanilla Ice Cream",
                            Price = 2.5
                        },
                        new
                        {
                            Id = 24,
                            IdCategory = 7,
                            Name = "Chocolate Ice Cream",
                            Price = 2.5
                        },
                        new
                        {
                            Id = 25,
                            IdCategory = 7,
                            Name = "Strawberry Ice Cream",
                            Price = 2.5
                        },
                        new
                        {
                            Id = 26,
                            IdCategory = 8,
                            Name = "Affogato",
                            Price = 5.5
                        },
                        new
                        {
                            Id = 27,
                            IdCategory = 8,
                            Name = "Irish Coffee",
                            Price = 6.0
                        });
                });

            modelBuilder.Entity("WinFormApp.Models.FoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("FoodCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tea"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Smoothies"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pastries"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sandwiches"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Juices"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ice Cream"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Specials"
                        });
                });

            modelBuilder.Entity("WinFormApp.Models.TableFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TableFoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Table 1",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Table 2",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Table 3",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Table 4",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Table 5",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Table 6",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Table 7",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Table 8",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Table 9",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Table 10",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Table 11",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Table 12",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Table 13",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Table 14",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Table 15",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Table 16",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Table 17",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Table 18",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Table 19",
                            Status = "Empty"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Table 20",
                            Status = "Empty"
                        });
                });

            modelBuilder.Entity("WinFormApp.Models.Bill", b =>
                {
                    b.HasOne("WinFormApp.Models.TableFood", "Table")
                        .WithMany("Bills")
                        .HasForeignKey("IdTable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WinFormApp.Models.BillInfo", b =>
                {
                    b.HasOne("WinFormApp.Models.Bill", "Bill")
                        .WithMany("BillInfos")
                        .HasForeignKey("IdBill")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WinFormApp.Models.Food", "Food")
                        .WithMany("BillInfos")
                        .HasForeignKey("IdFood")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WinFormApp.Models.Food", b =>
                {
                    b.HasOne("WinFormApp.Models.FoodCategory", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
